spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sbapp
  jpa:
    hibernate:
      ddl-auto: create-drop

logging.level:
  nl.rcomanne: DEBUG

words:
  init: true