spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    open-in-view: true
  jackson:
    default-property-inclusion: non_null

logging.level:
  nl.rcomanne: INFO

words:
  init: true