spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

management:
  server:
    port: 8081

logging.level:
  nl.rcomanne: INFO

words:
  init: true