spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

words:
  init: true