---
apiVersion: v1
kind: Service
metadata:
  namespace: services
  name: game-service
  labels:
    app: game-service
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
  selector:
    app: game-service